use_frameworks!

platform :ios, '10.0'

target 'LVVenderModule_Example' do
  pod 'LVVenderModule', :path => '../'

  target 'LVVenderModule_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
